title: <p align="center"> Yuvaraj DR </p>
logo: /assets/img/yuve_pool.jpg

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yuvarajdrhlk/">LinkedIn</a> |
  <a href="https://github.com/yuvarajdr">GitHub</a>
  
  <br>   
  I'm working on cloud application and some ML model. 
  I Like responsible and challenging position with 
  opportunities to enrich my knowledge and skills while 
  contributing to the success of the organization and to 
  build result-oriented professional growth. 
  <br>
  </p>